### ISSUE TITLE
Install fails for python 3.12

### ISSUE THREAD

**Issue by boidolr** [zyskarch/pytestarch#103]
Due to a incompatibility with numpy 1.24 installs on python 3.12 fail, see for example https://github.com/boidolr/pytestarch/actions/runs/9242411957/job/25425215500

To get a more recent version of numpy requires dropping python 3.8 support (which would also allow a number of other version updates, something like https://github.com/boidolr/pytestarch/pull/4).

**Comment by zyskarch** [comment]
Thank you for bringing this up! I've opened a PR for this, which I'll merge in the next couple of days and release a new version.
I noticed that you updated a lot of type hints in your fork - please feel totally free to open a PR for this as well, I'd be very happy to merge it ;)

**Comment by boidolr** [comment]
No problem, I've applied `ruff check --select UP .` for that :D
