### ISSUE TITLE
Does not run for python 3.8

### ISSUE THREAD

**Issue by finswimmer** [zyskarch/pytestarch#53]
Hello,

thanks a lot for this promising project :+1: 

During evaluation of `pytestarch` I discovered it is not running on Python 3.8. The reason is, that there are various places where `list` , `dict` or `set` are used for type annotations instead of `List`, `Dict` and `Set` from the `typing` package. This is supported for Python >= 3.9 only (see [PEP 585](https://peps.python.org/pep-0585/)).

For Python < 3.9 it is necessary to add `from __future__ import annotations` to each Python file. This can be done by `isort` if we use the `add_imports` option: `add_imports = ["from __future__ import annotations"]`.

I was willing to submit a PR for it. But unfortunately a lot of tests are failing, as soon as this import statements are added to the files. I don't understand enough how the package works under the hood, so it might be better if someone else tries to fix it :smiley: 

fin swimmer

**Comment by finswimmer** [comment]
I prepared #54. This one change all appearance of list , dict, set and tuple in type hints to there counter part in the `typing` module.

However, I don't know if the tests are failing when using `from __future__ import annotations` because of how the tests are structured or if there is a deeper problem.

**Comment by zyskarch** [comment]
Hello finswimmer,

thank you for reporting - and also fixing - the issue! 
I've recently noticed as well and started to exchange dict/list/... as well, but have not yet changed all of them.

The add_imports fix also causes a lot of tests to fail on my end, so I'd go with merging your fix for now, to make sure the package is usable for python 3.8.
