### ISSUE TITLE
Make matplotlib dependency optional

### ISSUE THREAD

**Issue by jakobkogler** [zyskarch/pytestarch#89]
Currently if you install this library, you automatically install all it's dependencies like `matplotlib` and `pyparsing`.
Those however are not needed for the core functionality (running architecture tests).

I would propose of making those diagram related libraries optional.
It's possible to do that with extras in Poetry: https://python-poetry.org/docs/pyproject/#extras

- `pip install pytestarch` should install just the core functionality (calling `.visualize()` should raise some missing-libraries exception).
- `pip install 'pytestarch[diagram]'` should additionally install matplotlib.

**Comment by zyskarch** [comment]
I've released a new version (2.0.0), which makes this possible. Thanks for the suggestion!
